### PR TITLE
feat: add global envVar from secret

### PR DESCRIPTION
**Pull request by joelp172**
Ability to add global envVars from a Secret. These will be exposed as environment variables to the Management Repository, Edge and Dacha deployments

### CODE REVIEW

**Comment by rvowles** [comment]
It needs the helmdocs run as well

**Comment by joelp172** [comment]
> It needs the helmdocs run as well, otherwise it looks excellent!

Thats done!

**Comment by rvowles** [comment]
Looks like maybe you didn't do a helm dependency update before doing the helm docs?

**Comment by joelp172** [comment]
> Looks like maybe you didn't do a helm dependency update before doing the helm docs?

Ah yes, I used the latest helm-docs version. I've used 1.11.0 to match the check's version

**Pull request merged**
