### PR TITLE
Add PodDisruptionBudget for dacha, edge and managementRepository

### PR DESCRIPTION
**Pull request by matejhasul**
We are missing PDB in our deployment.

Signed-off-by: Matej Hasul <matej.hasul@gooddata.com>

### CODE REVIEW

**Comment by matejhasul** [comment]
Should I bump also the chart version?

**Comment by matejhasul** [comment]
@rvowles @IrinaSouth would you mind checking this?

**Comment by rvowles** [comment]
yes @matejhasul - if you can bump the chart version we can merge it straight up and it will release the new version.

**Comment by rvowles** [comment]
Oh, and you also need to regenerate the docs and commit them in as well

**Comment by rvowles** [comment]
The helm doc generator is part of the github pipeline, the issue being we release on merge to main - so the docs need to be up to date :-) ref is here: https://github.com/featurehub-io/featurehub-helm/blob/main/.github/helm-docs.sh

**Comment by rvowles** [comment]
squashed on merge :-) thanks for your contribution @matejhasul !

**Comment by matejhasul** [comment]
@rvowles Thanks for quick review&merge.

**Pull request merged**
